FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /mockcarrier ./cmd/mockcarrier

FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /mockcarrier /mockcarrier
EXPOSE 8081
CMD ["/mockcarrier"]
